In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('diabetes.csv')

In [3]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [6]:
zero_columns = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
for col in zero_columns:
    df[col] = df[col].replace(0, np.nan)

print(df.isnull().sum())

Pregnancies                   0
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

In [7]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [8]:
for col in zero_columns:
    df[col].fillna(df[col].median(), inplace=True)

C:\Users\lahir\AppData\Local\Temp\ipykernel_20012\4185952643.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\lahir\AppData\Local\Temp\ipykernel_20012\4185952643.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\lahir\AppData\Local\Temp\ipykernel_20012\4185952643.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\lahir\AppData\Local\Temp\ipykernel_20012\4185952643.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\lahir\AppData\Local\Temp\ipykernel_20012\4185952643.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [9]:
for col in zero_columns:
    df[col].fillna(df[col].median(), inplace=True)

C:\Users\lahir\AppData\Local\Temp\ipykernel_20012\4185952643.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\lahir\AppData\Local\Temp\ipykernel_20012\4185952643.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\lahir\AppData\Local\Temp\ipykernel_20012\4185952643.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\lahir\AppData\Local\Temp\ipykernel_20012\4185952643.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\lahir\AppData\Local\Temp\ipykernel_20012\4185952643.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [10]:
for col in zero_columns:
    df[col] = df[col].fillna(df[col].median())

In [11]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,125.0,33.6,0.627,50,1
1,1,85.0,66.0,29.0,125.0,26.6,0.351,31,0
2,8,183.0,64.0,29.0,125.0,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [16]:
X = df.drop(columns=['Outcome'])

In [17]:
y = df['Outcome']

In [18]:
X

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148.0,72.0,35.0,125.0,33.6,0.627,50
1,1,85.0,66.0,29.0,125.0,26.6,0.351,31
2,8,183.0,64.0,29.0,125.0,23.3,0.672,32
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63
764,2,122.0,70.0,27.0,125.0,36.8,0.340,27
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30
766,1,126.0,60.0,29.0,125.0,30.1,0.349,47
767,1,93.0,70.0,31.0,125.0,30.4,0.315,23

In [19]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [20]:
from sklearn.preprocessing  import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print(X_scaled[0])

[ 0.63994726  0.86604475 -0.03198993  0.67064253 -0.18154124  0.16661938
  0.46849198  1.4259954 ]

In [22]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,125.0,33.6,0.627,50,1
1,1,85.0,66.0,29.0,125.0,26.6,0.351,31,0
2,8,183.0,64.0,29.0,125.0,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [25]:
print(f"Training දත්ත ප්‍රමාණය: {X_train.shape[0]}")
print(f"Testing දත්ත ප්‍රමාණය: {X_test.shape[0]}")

Training දත්ත ප්‍රමාණය: 614
Testing දත්ත ප්‍රමාණය: 154

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Model එක සාදා පුහුණු කිරීම
log_model = LogisticRegression()
log_model.fit(X_train, y_train)

# අනාවැකි ලබා ගැනීම
y_pred_log = log_model.predict(X_test)

# Accuracy එක බැලීම
log_acc = accuracy_score(y_test, y_pred_log)
print(f"Logistic Regression Accuracy: {log_acc * 100:.2f}%")
print("\nDetailed Classification Report:\n", classification_report(y_test, y_pred_log))

Logistic Regression Accuracy: 75.32%

Detailed Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.83      0.81        99
           1       0.67      0.62      0.64        55

    accuracy                           0.75       154
   macro avg       0.73      0.72      0.73       154
weighted avg       0.75      0.75      0.75       154

In [28]:
from xgboost import XGBClassifier

# Model එක සාදා පුහුණු කිරීම
xgb_model = XGBClassifier(random_state=42, eval_metric='logloss')
xgb_model.fit(X_train, y_train)

# අනාවැකි ලබා ගැනීම
y_pred_xgb = xgb_model.predict(X_test)

# Accuracy එක බැලීම
xgb_acc = accuracy_score(y_test, y_pred_xgb)
print(f"XGBoost Accuracy: {xgb_acc * 100:.2f}%")
print("\nDetailed Classification Report:\n", classification_report(y_test, y_pred_xgb))

XGBoost Accuracy: 71.43%

Detailed Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.74      0.77        99
           1       0.59      0.67      0.63        55

    accuracy                           0.71       154
   macro avg       0.69      0.71      0.70       154
weighted avg       0.73      0.71      0.72       154

In [29]:
def get_diabetes_recommendations(patient_data):
    # 1. Model එකෙන් දියවැඩියාව ඇතිවීමේ සම්භාවිතාව (Probability) ලබා ගැනීම
    # [0][1] මගින් Class 1 (දියවැඩියාව ඇතිවීම) සඳහා සම්භාවිතාව ලබාදෙයි
    risk_prob = log_model.predict_proba(patient_data)[0][1]
    risk_percentage = risk_prob * 100
    
    print(f"📊 ඔබේ දියවැඩියා අවදානම් මට්ටම (Diabetes Risk Rate): {risk_percentage:.2f}%\n")
    print("--------------------------------------------------")
    print("💡 වෛද්‍ය සහ ජීවන රටා උපදෙස් (Recommendations):")
    print("--------------------------------------------------")
    
    # 2. අවදානම අනුව උපදෙස් කාණ්ඩ කිරීම (Rule-based Logic)
    if risk_percentage < 30:
        print("✅ සුභ පැතුම්! ඔබේ අවදානම ඉතා අවම මට්ටමක පවතී.")
        print("* දැනට පවත්වාගෙන යන සෞඛ්‍ය සම්පන්න ජීවන රටාව ඉදිරියටත් රැකගන්න.")
        print("* දිනපතා ප්‍රමාණවත් පරිදි ජලය පානය කරන්න සහ ක්‍රියාශීලී වන්න.")
        
    elif 30 <= risk_percentage < 70:
        print("⚠️ මධ්‍යස්ථ අවදානමක් (Moderate Risk)! ප්‍රවේශම් විය යුතුයි.")
        print("* ආහාර වේලෙහි අඩංගු පැණිරස කෑම සහ කාබෝහයිඩ්‍රේට් (බත්, පාන් වැනි දෑ) සීමා කරන්න.")
        print("* දිනකට අවම වශයෙන් විනාඩි 30ක්වත් වේගයෙන් ඇවිදීම වැනි ව්‍යායාමයක නිරත වන්න.")
        print("* මාස 6කට වරක්වත් රුධිරයේ සීනි මට්ටම (Fasting Blood Sugar) පරීක්ෂා කරගන්න.")
        
    else:
        print("🚨 අධික අවදානමක් (High Risk)! වහාම ක්‍රියාත්මක වන්න.")
        print("* වහාම වෛද්‍යවරයකු (Doctor) හමුවී සම්පූර්ණ රුධිර පරීක්ෂණයක් සිදුකර උපදෙස් ලබාගන්න.")
        print("* සීනි සහ තෙල් අධික කෑම සම්පූර්ණයෙන්ම පාහේ නතර කරන්න.")
        print("* දෛනික කාර්යබහුලත්වය සහ මානසික ආතතිය (Stress) පාලනය කරගන්න.")

# උදාහරණයක් ලෙස Test set එකේ ඉන්න 5 වැනි රෝගියාගේ අවදානම පරීක්ෂා කරමු
test_patient = X_test[4].reshape(1, -1)
get_diabetes_recommendations(test_patient)

📊 ඔබේ දියවැඩියා අවදානම් මට්ටම (Diabetes Risk Rate): 46.24%

--------------------------------------------------
💡 වෛද්‍ය සහ ජීවන රටා උපදෙස් (Recommendations):
--------------------------------------------------
⚠️ මධ්‍යස්ථ අවදානමක් (Moderate Risk)! ප්‍රවේශම් විය යුතුයි.
* ආහාර වේලෙහි අඩංගු පැණිරස කෑම සහ කාබෝහයිඩ්‍රේට් (බත්, පාන් වැනි දෑ) සීමා කරන්න.
* දිනකට අවම වශයෙන් විනාඩි 30ක්වත් වේගයෙන් ඇවිදීම වැනි ව්‍යායාමයක නිරත වන්න.
* මාස 6කට වරක්වත් රුධිරයේ සීනි මට්ටම (Fasting Blood Sugar) පරීක්ෂා කරගන්න.

In [31]:
from sklearn.model_selection import GridSearchCV
from xgboost import XGBClassifier

# ටෙස්ට් කරන්න ඕන Parameters ලැයිස්තුව (Grid)
param_grid = {
    'n_estimators': [50, 100, 150],
    'max_depth': [3, 4, 5],                 # ගසේ ගැඹුර අඩු කිරීමෙන් Overfitting පාලනය වේ
    'learning_rate': [0.01, 0.1, 0.2],
    'subsample': [0.7, 0.8, 0.9]
}

xgb = XGBClassifier(random_state=42, eval_metric='logloss')

# GridSearchCV මගින් හොඳම සෙටින්ග්ස් සොයමු
grid_search = GridSearchCV(estimator=xgb, param_grid=param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)

# හොඳම Model එක ගනිමු
best_xgb = grid_search.best_estimator_

# අලුත් Accuracy එක බලමු
y_pred_grid = best_xgb.predict(X_test)
grid_acc = accuracy_score(y_test, y_pred_grid)
print(f"Tuned XGBoost Accuracy: {grid_acc * 100:.2f}%")
print("Best Parameters:", grid_search.best_params_)

Tuned XGBoost Accuracy: 75.97%
Best Parameters: {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 50, 'subsample': 0.8}

In [33]:
from imblearn.over_sampling import SMOTE
from sklearn.linear_model import LogisticRegression

# 1. SMOTE මගින් Training දත්ත සමතුලිත කිරීම
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

print(f"SMOTE වලට පෙර Class 1 ප්‍රමාණය: {sum(y_train == 1)}")
print(f"SMOTE වලට පසු Class 1 ප්‍රමාණය: {sum(y_train_resampled == 1)}")

# 2. සමතුලිත දත්ත මත අපේ Logistic Regression එක නැවත පුහුණු කිරීම
balanced_log_model = LogisticRegression(random_state=42)
balanced_log_model.fit(X_train_resampled, y_train_resampled)

# 3. අලුත් Accuracy එක බැලීම
balanced_acc = accuracy_score(y_test, balanced_log_model.predict(X_test))
print(f"\nSMOTE කළ පසු Logistic Regression Accuracy: {balanced_acc * 100:.2f}%")

SMOTE වලට පෙර Class 1 ප්‍රමාණය: 213
SMOTE වලට පසු Class 1 ප්‍රමාණය: 401

SMOTE කළ පසු Logistic Regression Accuracy: 70.78%